Uns#unhash now resolves from tokenURI
unstoppabledomains/resolution-go pull request #15
Opened 2021-10-26 22:07 UTC by sudoryan

Includes changes from #14

2021-11-01 14:07 UTC, DancingAxolotl requested changes

2021-11-01 14:07 UTC, DancingAxolotl commented on uns_test.go
> +// }
I think we should be able to uncomment this since `unhash` is fixed now.
Is there something else that is preventing us from uncommenting this test?

2021-11-01 14:08 UTC, DancingAxolotl commented
@sudoryan PR looks good, just one question regarding tests

2021-11-02 15:47 UTC, DeRain approved these changes
@sudoryan Looks great! But please, uncomment tests as @DancingAxolotl mentioned in comments above.

2021-11-04 04:23 UTC, sudoryan commented on uns_test.go
> +// }
https://metadata.staging.unstoppabledomains.com/metadata/0x40920d1d24c83454d9d64e6666927f3abb97b3fd67c7e1bf43de5c2f4297f3b8 returns empty name

2021-11-04 17:55 UTC, merged