Ryan/locations
unstoppabledomains/resolution-go pull request #17
Opened 2021-11-17 01:46 UTC by sudoryan

2021-11-23 10:42 UTC, DeRain commented on uns_service.go
> +	}
@DancingAxolotl Good idea! I think we will split this out once we will need to reuse this code.

2021-11-23 10:55 UTC, DeRain requested changes

2021-11-23 10:55 UTC, DeRain commented on uns.go
> +		isSupported, _ := c.IsSupportedDomain((domainName))
Calling isSupportDomain for each domain name in array will introduce length(domainName) amount of network queries which makes multicall usage useless. If domain is not supported - don't return an error - just return empty location for this domain name.

2021-11-23 10:55 UTC, DeRain commented on uns_builder.go
> +	l1Service.networkId = NetworkNameToId[cb.l1Network]
@sudoryan Just allow user to put networkId instead of network names

2021-11-24 04:38 UTC, sudoryan commented on uns_builder.go
> +	l1Service.networkId = NetworkNameToId[cb.l1Network]
unsBuilder.Build() currently takes in the network name. I don't think we should have the user pass in both the networkId and network name

2021-11-24 04:42 UTC, sudoryan commented on uns_builder.go
> +	l1Service.networkId = NetworkNameToId[cb.l1Network]
So should we replace the mappings in uns_config.go from networkName to networkId?

2021-11-30 00:15 UTC, merged