chore: resolution config updates
unstoppabledomains/resolution-go pull request #25
Opened 2022-08-01 00:51 UTC by enaqx

- Update Readme
- Update default provider configs from Infura to Alchemy
- Change rinkeby network to goerli

2022-08-02 21:58 UTC, sammyluo requested changes

2022-08-02 21:58 UTC, sammyluo commented on README.md
> +  ethContractBackend, _ := ethclient.Dial("https://eth-mainnet.alchemyapi.io/v2/RAQcwz7hhKhmwgoti6HYM_M_9nRJjEsQ")
Let's keep it consistent with other alchemy url
```suggestion
  ethContractBackend, _ := ethclient.Dial("https://eth-mainnet.g.alchemy.com/v2/RAQcwz7hhKhmwgoti6HYM_M_9nRJjEsQ")
```

2022-08-02 21:58 UTC, sammyluo commented on README.md
> +  var ethereumUrl = "https://eth-mainnet.alchemyapi.io/v2/" + alchemyApiKey
```suggestion
  var ethereumUrl = "https://eth-mainnet.g.alchemy.com/v2/" + alchemyApiKey
```

2022-08-02 21:58 UTC, sammyluo commented on uns_builder_test.go
> +	backendl1, _ := ethclient.Dial("https://eth-goerli.alchemyapi.io/v2/r3soltxtCL_KhZGl7EwWsWax5ll_MFTN")
```suggestion
	backendl1, _ := ethclient.Dial("https://eth-goerli.g.alchemy.com/v2/r3soltxtCL_KhZGl7EwWsWax5ll_MFTN")
```

2022-08-02 21:58 UTC, sammyluo commented on uns_builder_test.go
> +	backendl1, _ := ethclient.Dial("https://eth-goerli.alchemyapi.io/v2/r3soltxtCL_KhZGl7EwWsWax5ll_MFTN")
```suggestion
	backendl1, _ := ethclient.Dial("https://eth-goerli.g.alchemy.com/v2/r3soltxtCL_KhZGl7EwWsWax5ll_MFTN")
```

2022-08-02 21:58 UTC, sammyluo commented on uns_builder_test.go
> +	backendl2, _ := ethclient.Dial("https://eth-goerli.alchemyapi.io/v2/r3soltxtCL_KhZGl7EwWsWax5ll_MFTN")
```suggestion
	backendl2, _ := ethclient.Dial("https://eth-goerli.g.alchemy.com/v2/r3soltxtCL_KhZGl7EwWsWax5ll_MFTN")
```

2022-08-02 21:58 UTC, sammyluo commented on uns_builder_test.go
> +	backendl2, _ := ethclient.Dial("https://polygon-mumbai.g.alchemy.com/v2/EP3SMW2f-2FMABuWuEdHdxKq_v1_ww8")
Typo in the key `EP3SMW2f-2FMABuWuEdHdxKq_v1_ww82` (missing the ending `2`)

```suggestion
	backendl2, _ := ethclient.Dial("https://polygon-mumbai.g.alchemy.com/v2/EP3SMW2f-2FMABuWuEdHdxKq_v1_ww82")
```

2022-08-10 13:57 UTC, enaqx commented
@sammyluo Updated, please take a look.

2022-08-10 15:21 UTC, sammyluo approved these changes
LGTM! 🙌

2022-08-11 10:48 UTC, merged