docs: update readme sample
unstoppabledomains/resolution-go pull request #28
Opened 2022-08-23 02:03 UTC by enaqx

2022-08-23 15:24 UTC, sammyluo requested changes

2022-08-23 15:24 UTC, sammyluo commented on README.md
> +	uns, _ := resolution.NewUnsBuilder().SetEthereumNetwork("goerli").SetL2EthereumNetwork("mumbai").Build()
It's better to give prod example.

```suggestion
	uns, _ := resolution.NewUnsBuilder().SetEthereumNetwork("mainnet").SetL2EthereumNetwork("polygon").Build()
```

2022-08-23 15:24 UTC, sammyluo commented on README.md
>  )
We might also need to update the import to
```
"github.com/unstoppabledomains/resolution-go/v2"
```
since `SetL2EthereumNetwork` isn't supported in the default version

2022-08-25 03:34 UTC, sammyluo requested changes

2022-08-25 03:34 UTC, sammyluo commented on README.md
> +	uns, _ = resolution.NewUnsBuilder().Build()
```suggestion
	uns, _ := resolution.NewUnsBuilder().Build()
```

2022-08-25 03:36 UTC, enaqx commented on README.md
> +	uns, _ = resolution.NewUnsBuilder().Build()
It will break example since we already initialized uns before.

2022-08-25 03:42 UTC, sammyluo commented on README.md
> +	uns, _ = resolution.NewUnsBuilder().Build()
Ah yes! Sorry I missed that.

2022-08-25 03:43 UTC, sammyluo approved these changes
LGTM! 🚀 ⭐

2022-08-25 14:17 UTC, merged