Added ud client as proxy server
unstoppabledomains/resolution-go pull request #38
Opened 2023-02-26 18:20 UTC by tunguyennnnn

## Background

## Changes

## To Do

## Additional Deployment and/or Rollback Steps

## Code Review

This Pull Request was thoroughly reviewed and meets all Code Review Standards pertaining to:

- [ ] **Implementation** - satisfied acceptance criteria
- [ ] **Communication** - notified engineers/stakeholders about impactful changes
- [ ] **Error handling** - handled, logged & alerted on errors
- [ ] **Documentation** - wrote readable code & commits, documented unintuitive code
- [ ] **Testing** - unit & E2E test coverage, tested in staging, DB migrations backwards compatible
- [ ] **Security** - sanitized inputs, vetted dependencies, validated/secured API requests, no committed secrets
- [ ] **Performance** - optimized expensive algorithms & database queries

Please select all **applied** standards relevant to this PR.
## Confirmation

- [ ] **Assignee Confirmation** - I (the author) have filled out the template above
- [ ] **Reviewer Confirmation** - I (a/the reviewer) confirm 1) the author has filled out the template and checked the box that says **Assignee Confirmation** 2) I reviewed the code and selected all applicable items in the code review section.

2023-03-14 15:06 UTC, sammyluo commented on udclient/udclient.go
> +var proxyBaseUrl = "https://resolve.unstoppabledomains.com"
Shall we just use the new URL with API Gateway?

2023-03-14 15:37 UTC, sammyluo requested changes

2023-03-14 15:37 UTC, sammyluo commented on udclient/udclient.go
> +	agentHeader := rpc.WithHeader("x-lib-client", libClientHeaderString)
In the JS PR, you named this header as `X-Lib-Agent` instead of `x-lib-client`. Let's pick one and make them consistent.

2023-03-14 15:53 UTC, tunguyennnnn commented on udclient/udclient.go
> +var proxyBaseUrl = "https://resolve.unstoppabledomains.com"
👍 yea I was keeping this for testing. will update it!

2023-03-14 15:53 UTC, tunguyennnnn commented on udclient/udclient.go
> +	agentHeader := rpc.WithHeader("x-lib-client", libClientHeaderString)
yea will pick `X-Lib-Agent` 👍

2023-03-15 15:45 UTC, sammyluo requested changes

2023-03-15 15:45 UTC, sammyluo commented on udclient/udclient.go
> +	agentHeader := rpc.WithHeader("X-Lib-Client", libClientHeaderString)
```suggestion
	agentHeader := rpc.WithHeader("X-Lib-Agent", libClientHeaderString)
```

2023-03-15 16:00 UTC, sammyluo approved these changes
Nice! 🚀 ⭐

2023-03-15 16:02 UTC, merged