[DT 905] add ens support
unstoppabledomains/resolution-go pull request #46
Opened 2023-09-06 20:29 UTC by tunguyennnnn

## Background

## Changes

## To Do

## Additional Deployment and/or Rollback Steps

## Code Review

This Pull Request was thoroughly reviewed and meets all Code Review Standards pertaining to:

- [ ] **Implementation** - satisfied acceptance criteria
- [ ] **Communication** - notified engineers/stakeholders about impactful changes
- [ ] **Error handling** - handled, logged & alerted on errors
- [ ] **Documentation** - wrote readable code & commits, documented unintuitive code
- [ ] **Testing** - unit & E2E test coverage, tested in staging, DB migrations backwards compatible
- [ ] **Security** - sanitized inputs, vetted dependencies, validated/secured API requests, no committed secrets
- [ ] **Performance** - optimized expensive algorithms & database queries

Please select all **applied** standards relevant to this PR.
## Confirmation

- [ ] **Assignee Confirmation** - I (the author) have filled out the template above
- [ ] **Reviewer Confirmation** - I (a/the reviewer) confirm 1) the author has filled out the template and checked the box that says **Assignee Confirmation** 2) I reviewed the code and selected all applicable items in the code review section.

2023-09-15 15:22 UTC, DancingAxolotl requested changes
Nice work! It looks good overall, but there are some points we may want to discuss before merging

2023-09-15 15:22 UTC, DancingAxolotl commented on ens.go
> +	return nil, &MethodIsNotSupportedError{NamingServiceName: namingservice.ENS}
There are some DNS resolution methods which may be supported by some resolvers
https://github.com/unstoppabledomains/uns/blob/main/artifacts/abi/DNSResolver.json
Need to ask @DeRain for specific ABI methods to call

But probably okay to leave not supported for the initial release.

2023-09-15 15:22 UTC, DancingAxolotl commented on ens.go
> +func (e *Ens) Unhash(domainHash string) (string, error) {
I think we don't need the unhash function now
Especially for ENS

It was necessary for reverse resolution in UNS since RR would return you only the `node` value. So in order to get the plaintext name you needed some sort of `unhash` function.

ENS doesn't have this problem as it stores plaintext domain names as the RR value. (UNS too since recently, but that's another story)

2023-09-15 15:22 UTC, DancingAxolotl commented on ens_service.go
> +func (e EnsService) namehash(domainName string) common.Hash {
Isn't there a namehash function already for UNS? It should be the same for ENS and UNS

2023-09-15 15:22 UTC, DancingAxolotl commented on ens_service.go
> +func (e EnsService) labelNamehash(domainName string) common.Hash {
Probably just `labelhash` (AKA token id) since this is not a `namehash`

2023-09-15 15:22 UTC, DancingAxolotl commented on uns.go
> +	return time.Now().AddDate(100, 0, 0), nil
Why do we return a random date for UD expiry?
Maybe just return `nil`? Or throw `Unsupported` error?

2023-09-15 17:05 UTC, tunguyennnnn commented on ens.go
> +	return e.service.textRecord(resolverAddress, namehash, "avatar")
oh should that be contentHash?

2023-09-15 17:06 UTC, tunguyennnnn commented on ens.go
> +	return e.service.contenthashRecord(resolverAddress, e.service.namehash(domainName))
yea, :eyes:

2023-09-15 17:06 UTC, tunguyennnnn commented on ens.go
> +	return nil, &MethodIsNotSupportedError{NamingServiceName: namingservice.ENS}
yea on dns website they say their way of ENS is out of date

2023-09-16 15:58 UTC, tunguyennnnn commented on ens.go
> +		return "", nil
no, it should just simply mean no reverse record found, otherwise users of the lib would need to handle unnecessary error case

2023-09-16 20:24 UTC, tunguyennnnn commented on ens.go
> +	return e.service.contenthashRecord(resolverAddress, e.service.namehash(domainName))
is there docs for onion and others? I update to decode only ipfs and swarm for now from this guide doc https://eips.ethereum.org/EIPS/eip-1577

2023-09-16 20:24 UTC, tunguyennnnn commented on ens.go
> +	return e.service.textRecord(resolverAddress, namehash, "avatar")
updated to use contentHash

2023-09-16 20:25 UTC, tunguyennnnn commented on ens_service.go
> +func (e EnsService) labelNamehash(domainName string) common.Hash {
fixed

2023-09-16 21:07 UTC, tunguyennnnn commented on ens_service.go
> +	go e.getOwnerFromRegistry(namehash, ch)
yea I have the `go e.getOwnerFromNameWrapper(namehash, ch)` which fetch the real onwer or `logicalOwnerAddress` 1 line up

2023-09-16 21:17 UTC, tunguyennnnn commented on uns.go
> +	return time.Now().AddDate(100, 0, 0), nil
yea probably unsupported with Error, time or nil is not a GO idiom

2023-09-16 21:24 UTC, tunguyennnnn commented on zns.go
> +	return time.Now().AddDate(100, 0, 0), nil
fixed

2023-09-16 21:24 UTC, tunguyennnnn commented on ens.go
> +func (e *Ens) Unhash(domainHash string) (string, error) {
well it's implemented already anyway, it could be useful as template for other Raas 😄

2023-09-19 21:53 UTC, DancingAxolotl commented on ens.go
> +	return e.service.contenthashRecord(resolverAddress, e.service.namehash(domainName))
There is an `ens-contenthash` package, but you may need some fixes to get it to work
https://unstoppabledomains.slack.com/archives/CH28NMH6K/p1694792071676429

2023-09-19 22:01 UTC, DancingAxolotl commented on ens.go
> +	return e.service.textRecord(resolverAddress, namehash, "avatar")
Yeah, probably content hash. I think they also have a `url` text record, but not sure if that's the same

2023-09-19 22:03 UTC, DancingAxolotl approved these changes
Some minor comments but we can fix it later.
Otherwise LGTM! 🔥

2023-09-19 22:28 UTC, merged